#!/usr/bin/perl

#More-or-less constaint values...
my $imagePath = '/usr/share/games/xxkcd';
my $displayImage = '';

#Get file paths
my $configFolder = $ENV{"HOME"} . "/.xxkcd";
my $configFile = $configFolder . "/conf";
my $comicFileBase = $configFolder. "/comic";
my $comicNum = shift;
$comicNum .= "/" if $comicNum;

#Scrape xkcd
my $xkcdStuff = `curl https://xkcd.com/$comicNum`;


#  If the black hat image is installed, use it as the display image
if ( -e "$imagePath/blackhat.png" ) {
	$displayImage = "--image $imagePath/blackhat.png";
}

# Else, try to use a local version of blackhat
elsif ( -e 'blackhat.png' ) {
	print "Blackhat image isn't installed. Using a local version\n";
	$blackhat = '--image blackhat.png';
	$displayImage = "--image lackhat.png";
}

else {
	print "Couldn't find black hat. You get a cow.\n";
	$displayImage = '';
}

#Regex extraction of the comic file path
$xkcdStuff =~ m#(?<=src=")(//imgs\.xkcd\.com/comics/[^\s"]*)(?=")# or die `xcowsay $displayImage "Huh.  There's no picture there."`;
my $comicURL = "https:" . $1;
print "$comicURL\n";

#Get the title text. Probably my craziest regular expression yet.
$xkcdStuff =~ m#<img src=".*?".*?title=(["'])((?:[^\1]|\\(?:\\\\)*\1)*?)\1# or die `xcowsay $displayImage "Umm... I couldn't find any title text"`;
my $titleText = $2;
print $titleText;

#Make the configuration directory if it doesn't already exist
mkdir $configFolder unless -e $configFolder;

#Create the config file if it doesn't already exist
unless( -e $configFile ) {
	open CONFIG_FILE, ">", $configFile;
	print CONFIG_FILE "NONE";
	close CONFIG_FILE;
}

#Open the config file for reading
open CONFIG_FILE, "<", $configFile;
chomp(my $lastComic = <CONFIG_FILE>);
close CONFIG_FILE;

#Download the new comic
unless($comicURL eq $lastComic && $comicNum != 1335) {
	print "Downloading latest comic...\n";
	system "wget", "-O" => "$comicFileBase", "$comicURL";\
	open CONFIG_FILE, ">", $configFile;
	print CONFIG_FILE $comicURL;
	close CONFIG_FILE;
}

#Show the comic
`xcowsay $displayImage -d $comicFileBase `;
`xcowsay $displayImage "$titleText"`;

